### ISSUE TITLE
Meta selector $all for link relations

### ISSUE THREAD

**Issue by patrickjuchli** [basti1302/traverson-hal#6]
Thanks for the great library! I have a question regarding link relations:

For embedded arrays I can use the meta selector $all to receive an array of all embedded entries of a given type. It would be helpful to have the same thing for link relations with the same relation type as well.

Am I right in assuming this is currently not possible or am I missing something?

**Comment by patrickjuchli** [comment]
To clarify, for the link relations I'm interested in being able to getUrl(), to get the hrefs and not the actual resources referenced by those multiple link relations with same type.

**Comment by basti1302** [comment]
Hm, not sure about this.

For embedded entries, $all makes sense because we already have received all elements and need no further HTTP requests. For `get()` or `getDocument()`, all would require as many HTTP requests as there are link relations of the same type. I'm not sure if we should offer a meta selector that can trigger an arbitrary number of HTTP requests.

Of course, this is not the case for `getUrl()` but I also do not want to provide a meta selector that only works for `getUrl()`, but not for `get()` and `getResource()`. Also, what about post/put/patch/delete - would we post/put/patch/delete all linked resources?

OTOH, I can see the use case for this in the context of `getUrl()`.

**Comment by patrickjuchli** [comment]
I agree, only getUrl() makes sense. I do have a need for it in a current project, though. Currently, I'm getting the URLs "manually" from the reponse object but that is not exactly a good solution.

**Comment by basti1302** [comment]
Okay, whatever, +1 for making $all work for link relations for getUrl. Since I have no use case for this but you have: Do you think you could create a pull request for this? It should not be too big of a change, I guess.

**Comment by patrickjuchli** [comment]
Totally forgot to answer you, I'm very sorry. In the end, I didn't need this feature anymore. I would be fine with having this issue closed with "won't fix".
